
services:
  postgres:
    image: postgres:18-alpine
    container_name: starta_postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: starta
      POSTGRES_PASSWORD: starta_dev
      POSTGRES_DB: starta_db